// src/app/dashboard/materials/materials.js

export const materials = {
    active: [
      {
        id: 1,
        name: "Electrical Cables",
        quantity: 150,
        type: "Electrical",
        price: 500,
        source: "Powermax Electricals",
        supplier: "Maputo Hardware",
        transportCost: 700,
        transporter: "Citylink Delivery",
        dateReceived: "2024-07-01",
        description: "High-quality electrical cables for wiring",
        status: "In stock",
        category: "Electrical",
        unit: "rolls",
        lastUpdated: "2024-07-01",
      },
      {
        id: 2,
        name: "Cement",
        quantity: 100,
        type: "Construction",
        price: 150,
        source: "Cement Co.",
        supplier: "Maputo Hardware",
        transportCost: 300,
        transporter: "XYZ Logistics",
        dateReceived: "2024-07-02",
        description: "High-quality cement for construction",
        status: "In stock",
        category: "Construction",
        unit: "bags",
        lastUpdated: "2024-07-02",
      },
      {
        id: 3,
        name: "Steel Rods",
        quantity: 200,
        type: "Metal",
        price: 50,
        source: "ABC Metals",
        supplier: "Maputo Hardware",
        transportCost: 100,
        transporter: "FastTrack Delivery",
        dateReceived: "2024-07-03",
        description: "Steel rods for reinforcement",
        status: "In stock",
        category: "Metal",
        unit: "pieces",
        lastUpdated: "2024-07-03",
      },
    ],
    archived: [
      {
        id: 4,
        name: "Bricks",
        quantity: 300,
        type: "Construction",
        price: 200,
        source: "BrickWorks",
        supplier: "Maputo Hardware",
        transportCost: 150,
        transporter: "Brick Movers",
        dateReceived: "2024-06-15",
        description: "Red bricks for wall construction",
        status: "Archived",
        category: "Construction",
        unit: "pieces",
        lastUpdated: "2024-06-15",
      },
    ],
  };
  